fails 1
```
Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `my_lib` found (required by `my_app`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.1.0
```